### PR TITLE
General Enhancement

### PR DESCRIPTION
**Pull request by irish1986**
I have been using apt-cacher-ng for a while and notice a few improvement & enhancement could be made.  I am submitting this PR and welcoming C&C.

**Dockerfile**
- [Update Dockerfile - Bump to jammy-20221130](https://github.com/sameersbn/docker-apt-cacher-ng/commit/b1cfb462c3308b72197667a9c0fb05a4b69b92dc)

**Dependabot**
- [Create dependabot.yml](https://github.com/sameersbn/docker-apt-cacher-ng/commit/ea12921d01051e412d4df45074746d97fee182c2)

**Pod Configuration**
- [Update pod.yml - Add pull policy to pod configuration ](https://github.com/sameersbn/docker-apt-cacher-ng/commit/4b07727b27f902d06bd65f438b65e2302c55d537)
- [Update pod.yml - Add resources limits](https://github.com/sameersbn/docker-apt-cacher-ng/commit/4b07727b27f902d06bd65f438b65e2302c55d537)

**Build Workflow**
- [Update build.yml - Add platform to support arm64, armv6 and armv7](https://github.com/sameersbn/docker-apt-cacher-ng/commit/86e886927845a3c8b79be01eeff2dc1c3437fd47)
- [Update build.yml - Add GHA cache](https://github.com/sameersbn/docker-apt-cacher-ng/commit/316070bf61dc08b6702682138aad60e7a3092c97)

**Advanced Build Workflow**
I have added several steps in the build workflow, the goal is to create a temporary image for testing and scanning purpose before releasing the whole package.  It is obviously slightly overkill for the purpose of this package but some useful best practices to learn and leverage.
- [Update build.yml - Add a build step for testing and scanning](https://github.com/sameersbn/docker-apt-cacher-ng/commit/24d644650af8d7daf4693cc7b7a1cad14189aa66)
- [Update build.yml - Add scanning steps for security and vulnerability ](https://github.com/sameersbn/docker-apt-cacher-ng/commit/885e5b76a55fb8ccee870152caa20ecd9a1cf5ca)
- [Update build.yml - Add integration step using docker compose deployment](https://github.com/sameersbn/docker-apt-cacher-ng/commit/b8525102a2c0b04d2eaa6cf4ce0ca97c95e418e7)

### CODE REVIEW

**Comment by irish1986** [comment]
Any chance we could look into this PR?

**Comment by sameersbn** [comment]
thanks for the contribution

**Comment by sameersbn** [comment]
@irish1986 would you be interested in the maintenance of this image?

**Comment by irish1986** [comment]
> @irish1986 would you be interested in the maintenance of this image?

It could be interesting, it's a fairly stable image with once in a while update. Would you be transferring the entirety of it ownership (gh, docker, etc,..) or simply adding me as a contribution owner?

**Comment by sameersbn** [comment]
i'll add you as an collaborator, so you would be able to merge PR's

**Comment by irish1986** [comment]
> i'll add you as an collaborator

Sounds good, I think there was a mistake in my latest PR which broke the pipeline. I'll take a look at this later given it hasn't impacted the current distributed image.  I'll take a further look at the list of issue and see what i can do.

**Comment by sameersbn** [comment]
please accept my invitation. thanks for helping out.

**Pull request merged**
