### PR TITLE
Update the base image to jammy-20220421 and apt-cacher-ng to 3.7.4

### PR DESCRIPTION
**Pull request by gromain**
This PR updates the apt-cacher-ng image to the latest version of both apt-cacher-ng (3.7.4 at this time) and the base image to focal-20220113.

Also, as a simplification of the versioning, the version now references the base image version date, and not the actual build date.

### CODE REVIEW

**Comment by gromain** [comment]
Converted this PR to a draft for now.

apt-cacher-ng 3.7.4 is not available for Ubuntu focal.
Jammy is going to be the next LTS scheduled for release late april.

Until then this will stay a draft and will be updated once the final stable images for jammy are released.

**Comment by gromain** [comment]
With the release of jammy stable, this PR is now ready.
Commits have been squashed and cleaned up.
Version is consistent across all occurrences and references the current base image build date (version string is 3.7.4-20220421).

**Comment by gromain** [comment]
Image is verified to work with [gromain/apt-cacher-ng:autobuild](https://hub.docker.com/r/gromain/apt-cacher-ng).

Also, should close #31.

**Comment by gromain** [comment]
Any needed changes on my side? Did you have time to test @sameersbn ?

**Comment by gromain** [comment]
@sameersbn would you accept merging this? Is there anything needed on my side?

**Comment by guenhter** [comment]
@sameersbn  Is there anything what blocks this MR from being merged?

**Comment by sameersbn** [comment]
thanks for the contribution

**Comment by gromain** [comment]
My pleasure! Thanks for merging!

**Pull request merged**
