### PR TITLE
update to ubuntu disco with apt-cacher-ng 3.2

### PR DESCRIPTION
**Pull request by russkel**
In order to update to 3.2 you have to use a newer version of ubuntu. Seeing as there is no newer LTS I went for the latest ubuntu version.

### CODE REVIEW

**Comment by russkel** [comment]
Fair enough :thinking:

**Comment by sameersbn** [comment]
Hey sorry about this. 
For the longevity of the image I prefer to stick to LTS releases. Is there any specific bugfix/feature in 3.2  that prompts this update?

**Comment by russkel** [comment]
Not particularly. I don't know how apt-cacher works but from what I've seen it's probably not super high quality software as well as the age of it and lack of development. Mainly for security, I guess.

It's not backported, is it?

**Comment by sameersbn** [comment]
My understanding is LTS releases only bump PATCH versions for packages, while back porting  important security fixes.

**Comment by russkel** [comment]
Sure. I'll close this then.

**Pull request closed without merging**
